version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: backend_local_django
    container_name: backend_local_django
    volumes:
      - .:/app:z
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start

  docs:
    image: backend_local_docs
    container_name: backend_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./backend:/app/backend:z
    ports:
      - "9000:9000"
    command: /start-docs
