# Generated by Django 3.2.13 on 2023-04-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='step1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Registration step 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='step2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Registration step 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='step3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Registration step 3'),
        ),
    ]
